# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: llejeune <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/09 11:06:58 by llejeune          #+#    #+#              #
#    Updated: 2018/11/09 12:18:32 by llejeune         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRC = ft_display_file.c

all:
	gcc -Wall -Wextra -Werror $(SRC) -o $(NAME)
clean:
	
fclean:
	rm -f $(NAME)
